### ISSUE TITLE
Matriculaciones - agregar nueva matriculación 

### ISSUE THREAD

**Issue by Silvinagabriela** [RedTICS/matriculaciones#32]
MATRICULACIONES

### Comportamiento actual
El botón "agregar matriculación" No devuelve ninguna respuesta, no es posible continuar o agregar matriculación,
### Resultado esperado 
Agregar matriculación
### Pasos para reproducir el problema 
1. hacer clic en turnos
2. hacer clic en un turno
3. hacer clic en ver profesional
4. clic en formación de posgrado
5. clic en el icono de información (i)
6. clic en agregar nueva matriculación (+)
7.clic en confirmar
8. clic en ok...
![error matriculaciones](https://user-images.githubusercontent.com/38788179/43651068-bf923a3a-9717-11e8-8b0a-afa0cf5d39e2.PNG)
![err](https://user-images.githubusercontent.com/38788179/43651111-dc8a11e4-9717-11e8-8748-739a7c195fb0.PNG)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by milagrosn** [comment]
La prestación debe estar cargada previamente para poder agregar matriculación nueva.

**Comment by milagrosn** [comment]
cambió del sistema para agregar especialidad y numeración.
