### ISSUE TITLE
Impresión de turnos del día

### ISSUE THREAD

**Issue by milagrosn** [RedTICS/matriculaciones#76]
Tener la posibilidad de imprimir los turnos del día  (como se imprime la planilla de las agendas de CITAS por ejemplo).

![image](https://user-images.githubusercontent.com/39344609/49664303-3a66f400-fa30-11e8-8efe-1717bab0ebbb.png)

**Comment by palita1991** [comment]
Resuelto en PR https://github.com/RedTICS/matriculaciones/pull/78
