### ISSUE TITLE
Mejora: Visualización de turnos disponibles

### ISSUE THREAD

**Issue by milagrosn** [RedTICS/matriculaciones#80]
Cuando el profesional quiere sacar turno y están todos dados, no se distinguen los botones grisados (turnos no disponibles). Surge la necesidad a partir de un turno que quiso sacar un profesional (5 de enero) y no habían turnos hasta mediados de febrero, y la apariencia del sistema para el profesional era que no estaba funcionando el sistema, ya que probó todo enero y se mostraban los turnos grisados por lo tanto no podía sacar turno.

**Comment by palita1991** [comment]
Arreglado en PR https://github.com/RedTICS/matriculaciones/pull/78
